const mockProducts = [
  {
    id: 1,
    name: "top deportivo",
    category: "gym",
    price: 15000,
    stock: 10,
    img: "https",
  },
  {
    id: 2,
    name: "zapatillas",
    category: "running",
    price: 200000,
    stock: 15,
    img: "https",
  },
  {
    id: 3,
    name: "remera corta",
    category: "gym",
    price: 80000,
    stock: 7,
    img: "https",
  },
  {
    id: 4,
    name: "gorra",
    category: "accesorios",
    price: 30000,
    stock: 5,
    img: "https",
  },
  {
    id: 5,
    name: "pulsera",
    category: "accesorios",
    price: 10000,
    stock: 5,
    img: "https",
  },
  {
    id: 6,
    name: "pantalon corto",
    category: "gym",
    price: 40000,
    stock: 20,
    img: "https",
  },
  {
    id: 7,
    name: "pantalon largo",
    category: "running",
    price: 55000,
    stock: 5,
    img: "https",
  },
  {
    id: 8,
    name: "bolso",
    category: "accesorios",
    price: 45000,
    stock: 40,
    img: "https",
  },
  {
    id: 9,
    name: "abrigo",
    category: "running",
    price: 60000,
    stock: 10,
    img: "https",
  },
];

export default mockProducts;
